# @package _global_
model:
  type: "decision_tree"
  params:
    criterion: entropy
    max_depth: 6
    min_samples_split: 5
    min_samples_leaf: 3
    random_state: ${seed}

  log_feature_importance: true
  max_features_to_plot: 20