# @package _global_
model:
  type: "random_forest"
  params:
    n_estimators: 200
    max_depth: 30
    min_samples_split: 10
    min_samples_leaf: 5
    max_features: "sqrt"
    class_weight: "balanced"
    random_state: ${seed}
    n_jobs: -1

  log_feature_importance: true
  max_features_to_plot: 20