# @package _global_
model:
  type: "xgboost"
  params:
    n_estimators: 300
    max_depth: 6
    learning_rate: 0.1
    random_state: ${seed}
    n_jobs: -1
    eval_metric: "aucpr"

  log_feature_importance: true
  max_features_to_plot: 20