defaults:
  - model: random_forest
  - preprocessing: smote
  - data: local
  - _self_

experiment:
  name: "fraud-detection-experiments"
#  base_path: "/Users/your_email@company.com"
#  description: "Breaking the 0.75 recall ceiling"

mlflow:
  tracking_uri: "databricks"
  experiment_name: "${experiment.name}"

seed: 42